spring:
  profiles:
    active:
      develop
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate

ppb:
  files:
    upload:
      directory: ""