spring:
  profiles: develop
  datasource:
    url: jdbc:mysql://localhost:3306/personal_page_db_develop
    username: root
    password:

name: develop-YAML
environment: develop
server:
  port: 8085
  
ppb:
  files:
    upload:
      directory: "C://temp//"